image: gitpod/workspace-full:latest

ports:
- port: 8080
  onOpen: open-preview
- port: 8000
  onOpen: open-preview
- port: 8089
  onOpen: open-preview
- port: 8191
  onOpen: open-preview
- port: 9997
  onOpen: open-preview
- port: 8065
  onOpen: open-preview
tasks:
  - init: |
      # Install dependencies
      sudo apt-get update
      sudo apt-get install -y wget
  - command: |
      
      if ! id -u splunk > /dev/null 2>&1; then
        sudo useradd --create-home --shell /bin/bash splunk
      fi
      
      # Download Splunk Enterprise
      wget -O splunk-9.0.4.1-419ad9369127-Linux-x86_64.tgz "https://download.splunk.com/products/splunk/releases/9.0.4.1/linux/splunk-9.0.4.1-419ad9369127-Linux-x86_64.tgz"

      # Install Splunk Enterprise
      sudo mkdir /opt/splunk/
      sudo chown -R splunk:splunk /opt/
      sudo chmod 644 /workspace/Splunk_installation/splunk-9.0.4.1-419ad9369127-Linux-x86_64.tgz
      sudo tar -xvzf /workspace/Splunk_installation/splunk-9.0.4.1-419ad9369127-Linux-x86_64.tgz -C /opt/
      sudo chown -R splunk:splunk /opt/splunk/
      sudo chmod -R 644 /opt/splunk/*
      sudo cp /opt/splunk/etc/splunk-launch.conf.default /opt/splunk/etc/splunk-launch.conf
      sudo -u splunk echo "OPTIMISTIC_ABOUT_FILE_LOCKING = 1" >> /opt/splunk/etc/splunk-launch.con

      # Start Splunk and enable on boot
      sudo /opt/splunk/bin/splunk enable boot-start -user splunk
      sudo /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt

      # Open the Splunk web interface
      echo "Splunk is now running and available at: https://$(gp url 8000)"
