ports:
- port: 8080
  onOpen: open-preview
- port: 8000
  onOpen: open-preview
- port: 8089
  onOpen: open-preview
- port: 8191
  onOpen: open-preview
- port: 9997
  onOpen: open-preview
tasks:
- name: Terminal
  command: |
    echo "Creating the Splunk user"
    sudo useradd splunk
    echo "Creating the Splunk directory"
    sudo mkdir /opt/splunk/
    sudo chown -R splunk:splunk /opt/
    echo "Downloading the Splunk package"
    wget -O wget -O splunk-9.0.4.1-419ad9369127-Linux-x86_64.tgz "https://download.splunk.com/products/splunk/releases/9.0.4.1/linux/splunk-9.0.4.1-419ad9369127-Linux-x86_64.tgz"
    echo "Installing package"
    sudo chmod 644 /workspace/Splunk_installation/splunk-9.0.4.1-419ad9369127-Linux-x86_64.tgz
    sudo tar -xvzf /workspace/Splunk_installation/splunk-9.0.4.1-419ad9369127-Linux-x86_64.tgz -C /opt/

